### ISSUE TITLE
extractMoreauBroto

### ISSUE THREAD

**Issue by VeenaPulicharla** [nanxstats/protr#26]
Hi, I don't belong to Bioinformatics background, I am trying this package for some project, I have peptide sequences, I would like to derive some features from it to use as input to machine learning model. Could someone explain the reason for this error,
"extractMoreauBroto: length of the sequence is <= nlag; NAs will be generated",

why it doesn't accept sequences with shorter length ?

what are the min and max limits for sequence length limits?

I have many sequences with length in range of 5 to 25, how to extract features from these sequences, any suggestions?

**Comment by nanxstats** [comment]
Hi @VeenaPulicharla -please read the docs https://nanx.me/protr/reference/extractMoreauBroto.html. The default `nlag` is 30, so for sequences with a much shorter length (5 to 25), you could try a value smaller than 5.
