### ISSUE TITLE
not able to read FASTA file using Protr package 

### ISSUE THREAD

**Issue by arjunpuri7** [nanxstats/protr#28]
sir,
   i am presently working on protiens and try to use your package called protr. and not able to read fasta file as i follow the following likes of code:
library('protr')
extracell <- readFASTA(system.file(
  "protseq/extracell.fasta",
  package = "protr"
))
and display error:
Error in readFASTA(system.file("/project/e_target.fasta", package = "protr")) : 
  no line starting with a > character found
In addition: Warning message:
In file(con, "r") :
  file("") only supports open = "w+" and open = "w+b": using the former

please help me out from this problem

**Comment by nanxstats** [comment]
[`system.file()`](https://stat.ethz.ch/R-manual/R-devel/library/base/html/system.file.html) only reads files in packages.
