### ISSUE TITLE
Can't read FASTA sequences in the R package

### ISSUE THREAD

**Issue by rohitfarmer** [nanxstats/protr#32]
Hi there, thanks for providing this package. I am trying to use the locally installed R packages as I have quite a few sequences. And I am getting the following error.

```
> x <- readFASTA(system.file("results/train_lt_221.fasta",package = "protr"))
Error in readFASTA(system.file("results/train_lt_221.fasta", package = "protr")) : 
  no line starting with a > character found
In addition: Warning message:
In file(con, "r") :
  file("") only supports open = "w+" and open = "w+b": using the former
```
The same FASTA file works fine if I upload it to your server or use the shiny app locally. I am okay with using the shiny app, but I wonder what I am doing wrong here.

**Comment by nanxstats** [comment]
@rohitfarmer Please try something like `readFASTA("results/train_lt_221.fasta")` with your FASTA file path directly. The call `system.file(..., package = "protr")` is used to return the path to example data files from the installed package.

**Comment by Sohambiswas8** [comment]
Hi, @nanxstats , thank you for the suggestion. I was facing the same issue and now fixed it. But, can you add it in the protr HTML page (https://cran.r-project.org/web/packages/protr/vignettes/protr.html) that whoever has the data and script files in the same directory, can omit the "system.file( )" function in readFASTA( )? 

The 'protr' package is extremely helpful for feature selections directly from sequences as well as the manual.   
Thanking you,
Soham

**Comment by nanxstats** [comment]
> Hi, @nanxstats , thank you for the suggestion. I was facing the same issue and now fixed it. But, can you add it in the protr HTML page (https://cran.r-project.org/web/packages/protr/vignettes/protr.html) that whoever has the data and script files in the same directory, can omit the "system.file( )" function in readFASTA( )?
> 
> The 'protr' package is extremely helpful for feature selections directly from sequences as well as the manual. Thanking you, Soham

Thanks! It's already addressed by PR https://github.com/nanxstats/protr/pull/31.
