### ISSUE TITLE
crossSetSim() function

### ISSUE THREAD

**Issue by ofleitas** [nanxstats/protr#38]
Is it possible in future versions of protr to enable batches and verbose options for the crossSetSim() function?

**Comment by nanxstats** [comment]
That's entirely possible - adding `batches` and `verbose` to `crossSetSim()` and maybe also implement a disk-based version `crossSetSimDisk()` would be great additions - modeling after the existing `parSeqSim*()` functions.

I currently don't have the time to work on this. Are you interested in sending a pull request? Let me also copy the `crossSetSim()` author @seb-mueller in case he is interested.

**Comment by nanxstats** [comment]
@ofleitas This is now implemented in #41. I will make a release (1.7-1) to CRAN soon.
